### ISSUE TITLE
share editable files for PCB?

### ISSUE THREAD

**Issue by amchagas** [jfrie/FARESHARE#1]
Hi!

thanks for putting up all the doc for this device, really cool and well outlined! 

we are looking into implementing the system for mice for one of the labs in Sussex, and we also thought about adding a load cell to the system so we can automatically weight the animals. for that it would be useful to have editable files for the PCB... is this something you could share? which softwrae did you use to create it? Thanks!

**Comment by jfrie** [comment]
Hey,

Great point! Definitely an oversight. I've now uploaded an .fzz file to the GitHub so it can be easily modified. I made it in Fritzing.

Cheers,
Jude


Jude Frie | PhD

The Khokhar Lab, Department of Biomedical Sciences

University of Guelph, Ontario, Canada

________________________________
From: Andre Maia Chagas ***@***.***>
Sent: Wednesday, April 17, 2024 9:31 AM
To: jfrie/FARESHARE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jfrie/FARESHARE] share editable files for PCB? (Issue #1)


CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to ***@***.***


Hi!

thanks for putting up all the doc for this device, really cool and well outlined!

we are looking into implementing the system for mice for one of the labs in Sussex, and we also thought about adding a load cell to the system so we can automatically weight the animals. for that it would be useful to have editable files for the PCB... is this something you could share? which softwrae did you use to create it? Thanks!

**Comment by amchagas** [comment]
thanks!
